apiVersion: v1
kind: Deployment
metadata:
  name: jsr
  labels:
    name: jsr
spec:
  containers:
  - name: jsr
    image: nginx
    ports:
      - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: jsr
spec:
  selector:
    app: jsr
  ports:
  - port: 82
    targetPort: 80
  type: LoadBalancer
